### ISSUE TITLE
Supported Streams?

### ISSUE THREAD

**Issue by derFrickler** [AllanGallop/mini-web-radio#4]
Hi, 
Great Project, just what i wanted to have for my Basement (and maybe toilet ;-) )

I did not find any details on the supported radio streams. 
Which kind of streams are supported? mp3, icecast, shouldcast?

**Comment by AllanGallop** [comment]
Hi, 
Thank you so much

The audio is based on [ESP32-audioI2S](https://github.com/schreibfaul1/ESP32-audioI2S) which supports WAV, MP3, M4A, Icy-Stream and GoogleTTS. Shoutcast should work, along with other that support setting content type of the stream as a query parameter in the url
