### ISSUE TITLE
Powered by micro USB without batteries.

### ISSUE THREAD

**Issue by mikronwfh** [AllanGallop/mini-web-radio#8]
Hi! All I did was remove line 49 from the script.

1. What can I do next to use micro USB power only. I will never use battery power.
2. Where to connect the potentiometer in this case?
3. Can speakers above 3W be inefficient and will play unstable thanks to the radio?

![mini_web_radio](https://github.com/AllanGallop/mini-web-radio/assets/108129886/2cfc4e3a-bce7-445b-a894-e69a00c46bbc)

**Comment by AllanGallop** [comment]
Hi,
I've created a [new branch](https://github.com/AllanGallop/mini-web-radio/tree/no-battery) with a modified firmware INO file and a schematic change (see the readme). This removes the need for the battery LED (R3 and D2) along with omitting the battery sense circuit (R1/R2) and instead connecting the switch between the 3v3 rail and GPIO pin 33 to sleep/wake the ESP32.

**Comment by AllanGallop** [comment]
To answer your questions more directly:

1. Use the new branch and modification to remove the battery and it's associated parts
2. The potentiometer remains unchanged however the switch side of it connects directly between 3v3 and Pin 33
3. The maximum output of the I²S module is 3W so if using a 4Ω speaker you want it to have a power rating equal or greater than 3W (>1.5W for an 8Ω speaker). If attempting to drive an exceptionally large speaker the module may have issues actuating the voice coil

**Comment by mikronwfh** [comment]
thank you very much.  I'll let you know how it works when I test it :)

**Comment by mikronwfh** [comment]
Can I connect the aux socket instead of the speaker to output the sound to the receiver and amplifier?

**Comment by AllanGallop** [comment]
You can but bare in mind the output is mono not stereo, if that's not an issue you can bridge the channels to drive a stereo system. If it needs to be line level then you'd need to put in a voltage divider between the audio output and line in such as this:
https://www.circuitlab.com/editor/#?id=x5r3s4exfgzp

**Comment by mikronwfh** [comment]
> Hi, I've created a [new branch](https://github.com/AllanGallop/mini-web-radio/tree/no-battery) with a modified firmware INO file and a schematic change (see the readme). This removes the need for the battery LED (R3 and D2) along with omitting the battery sense circuit (R1/R2) and instead connecting the switch between the 3v3 rail and GPIO pin 33 to sleep/wake the ESP32.

I understand that there is no option to use the microUSB that we have on the ESP32 board to power the radio? I have to make a new one and connect it to 3v3 and 33?

**Comment by mikronwfh** [comment]
![MWR_no_bat](https://github.com/AllanGallop/mini-web-radio/assets/108129886/ffc3d567-df6c-445f-9457-90aaca1e5411)

**Comment by AllanGallop** [comment]
> I just copied the new MWR.ino file and the rest remains unchanged? I have this message right now. ![MWR_no_bat](https://user-images.githubusercontent.com/108129886/258655594-ffc3d567-df6c-445f-9457-90aaca1e5411.png)

My mistake, it should read as ``` if(digitalRead(POWER_SW) == LOW)```, I have updated the branch to reflect this. Yes the remaining structure is unchanged, if you remove the extra ```=``` from the if statement it should compile

**Comment by mikronwfh** [comment]
I'll check it and let you know. Meme also another problem. After installing IDE 2.0, I had ESP32 visible immediately under COM when I connected it to USB. Now I threw out all arduino ide directories and installed v 1.8.16 again and in Tool >> Port I have inactive. Nothing happens in the device manager either when I connect the ESP32. Fix it ASAP.

**Comment by AllanGallop** [comment]
I cannot comment on issues regarding the Arduino IDE or ESP libary, nor fix them as I am not a contributor or owner of those projects.

**Comment by mikronwfh** [comment]
> 
Done and it works. I replaced the USB cable with another one.

**Comment by mikronwfh** [comment]
![nobattery](https://github.com/AllanGallop/mini-web-radio/assets/108129886/b0d4abc4-013b-4ced-b591-ae17a325cfc9)

Not too many exits? There is not so much on my WEMOS ESP32.
So I don't know if I'm doing it right. I understand that the microUSB on the WEMOS ESP32 board will supply power after switching it on with a potentiometer? Should I put a microUSB between the GPIO and the potentiometer?

![ESP32 WEMOS LITE](https://github.com/AllanGallop/mini-web-radio/assets/108129886/4e8b55ee-56d0-4071-98b6-2552136c8cbb)

**Comment by mikronwfh** [comment]
I do not know how to connect the potentiometer with the entire ESP32 system in the new version. Instead of a battery, I have a USB cable with two wires +/- prepared. Only USB is 5V, and in the old scheme with the battery it is 3.7V. A new scheme for connecting the potentiometer with ESP32 would make it much easier for me. And should I have the power supply from the ESP32 board as it is in the old scheme, or can I use the microUSB power supply?

![_20230807_230211](https://github.com/AllanGallop/mini-web-radio/assets/108129886/351d11a9-cbbe-46f9-b6fb-26b8632e1227)
![_20230807_230230](https://github.com/AllanGallop/mini-web-radio/assets/108129886/abfedcc7-161b-4e0a-a14a-fa4c39efd6fc)

**Comment by AllanGallop** [comment]
![lolin32_mwr_no-batt](https://github.com/AllanGallop/mini-web-radio/assets/51855611/26fb0b6d-025d-4967-b88f-2009adf99000)

Hi, hopefully this clears it up for you. I've omitted the additional parts for simplicity

**Comment by mikronwfh** [comment]
the potentiometer has 5 legs.  if one is bridged, there are 4 remaining. and in the diagram I have 3 connections going to the potentiometer.

**Comment by AllanGallop** [comment]
You have a switched potentiometer which contains both a switch and potentiometer, the two pins on the back are the switch, the remaining 3 tabs on the side are the potentiometer; with knob facing you they are left connects to ground, center goes to pin 34, and right to 3v). you may bridge one of the switch pinsto the right (3v) leg to reduce need for multiple 3v wires with the remaining switch pin connected to pin 33

**Comment by mikronwfh** [comment]
First of all, thank you very much for your commitment to running.
I just finished my project according to your idea. :) Wow! It works! :))

https://youtu.be/Dh8_dGSo-cg

One thing that puzzles me is whether the diode on the ESP32 board (LED charging bat) should be lit after turning off the power using the potentiometer? This blue diode on 5 GPIO goes out, but the factory one on the board quickly pulses with blue light.

![mini-web-radio GOTOWY PROJEKT 08 2023](https://github.com/AllanGallop/mini-web-radio/assets/108129886/3830002b-2e91-4bcd-a1cc-4011730aad18)
